version: '3'

services:
  redis:
    image: redis
  cnc:
    build: .
    command: cnc --port 1337
    environment:
      COMIX_REDISADDRESS: redis:6379
      COMIX_REDISDBNUMBER: 0
      COMIX_UPDATEDISTRIBUTIONURL: "${COMIX_UPDATEDISTRIBUTIONURL}"
    depends_on:
      - redis
    ports:
      - "1337:1337"
